#!/bin/sh

set -e

MNT=/mnt/keys
if [ ! -e $MNT ]; then
    mkdir -p $MNT
    sleep 3
fi

USBDEVICE=/dev/disk/by-label/KEYS
if mount $USBDEVICE $MNT 2>/dev/null; then
    if [ -e $MNT/Luks/$CRYPTTAB_KEY.key ]; then
        cat $MNT/Luks/$CRYPTTAB_KEY.key
        umount $USBDEVICE
        echo "Success loading key file for {$CRYPTTAB_KEY} . Moving on." >&2

        exit
    fi

    umount $USBDEVICE
fi

/lib/cryptsetup/askpass "Insert pass key and press ENTER: "
